theme: jekyll-theme-artsy
source: _content/ 

plugins:
  - jekyll-thumbnail

nav:
- GALLERY: "/art/"
- SHOP: "/shop/"
- BLOG: "/blog/"
- TUTORIALS: "/tutorials/"
- SERVICES: "/services/"
- CONTACT: "/contact/"